### ISSUE TITLE
Add support for Postgres replicas

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#1338]
#### **Background / Current Limitation**

Sequin relies on the Postgres function (14+) `pg_logical_emit_message` to emit logical “heartbeat” WAL messages:

1. **Replication path** – heartbeats measure latency and safely advance WAL even if no tables pertaining to the publication+slot are changing.
2. **Backfill path** – those same WAL messages act as water-marks that let us deterministically order backfill rows with live replication events. ([More here](https://blog.sequinstream.com/using-watermarks-to-coordinate-change-data-capture-in-postgres/))

`pg_logical_emit_message` cannot be invoked on a **stand-by/replica** because replicas are always in *recovery mode*. Consequently Sequin today only works when users connect us to a **primary** Postgres instance.

---

#### **Goal**

Add first-class support for syncing **from a replica** by letting Sequin call `pg_logical_emit_message` on the *primary* while everything else (logical decoding, slot consumption, backfill scans) continues to run against the replica.

---

#### **High-level Approach**

| Plane | What changes | Key components |
| -- | -- | -- |
| **Data plane** | Detect when a configured Postgres connection is a replica and, when so, transparently use a *secondary/primary* connection **only** for emitting logical messages. | `SlotProcessorServer`, `TableReaderServer` |
| **Control plane** | Expose the extra connection in our API, YAML, and UI as an *optional* “primary connection” field that appears **only** when the DB is marked “Replica.” | API schema, YAML schema, React UI |

---

#### **Detailed Tasks**

1. **Schema / Config**
   * Add `primary_connection` (JSONB) to `postgres_databases` or create a new `primary_connections` table keyed by `database_id`.
   * Migrations + DDL.
   * (Is `primary_connection` right name? How do we store it? Brainstorm with an LLM)
2. **Data-plane code changes**
   * **Connection detection**
     * in `CheckPostgresReplicationSlotWorker`, run `SELECT pg_is_in_recovery();`.
     * If **true** and no `primary_connection` present, surface a health error (see §5).
   * **Replication path** – in `SlotProcessorServer`, use `primary_connection` exclusively when calling `pg_logical_emit_message`.
   * **Backfill path** – same change in `TableReaderServer`.
3. **API / YAML**
   * Extend `POST /databases` and `PATCH /databases/:id` with

     ```
     databases:
       - name: "my-database"          # Required, unique identifier
         username: "postgres"         # Default: postgres
         password: "postgres"         # Default: postgres
         hostname: "localhost"        # Required
         port: 5432                  # Default: 5432
         database: "my_database"     # Required
         pool_size: 10               # Default: 3
         slot_name: "sequin_slot"    # Required
         publication_name: "sequin_pub" # Required
         primary:  # What's the right name? New field on databases
           host:
           port:
           user:
           password:
           sslmode:
     
     ```
   * Validation: When `primary` present, `primary.*` field **required**.
4. **UI**
   * *Toggle*: “**Is replica?**”
     * Off → hide primary-connection fields.
     * On → show & require them.
   * *Auto-detect*: If user clicks **Test Connection** and we discover the DB is a replica, automatically flip the toggle **on** and prompt for the missing primary creds.
5. **Health & Observability**
   * `CheckReplicationSlotWorker`: when `pg_is_in_recovery()` is true **and** `replica=false` in our config, emit a `Health.Event` health event directing the user to edit the config.
   * This will display a helpful error to them right away after create on the Database Show page if they did not flip on "is replica" toggle.

---

#### **Acceptance Criteria**

* A replica-only connection successfully streams logical changes while heartbeats/backfills are emitted via the primary.
* UI enforces all required primary fields when *Replica* is enabled or auto-detected.
* Health event surfaces misconfigurations \~right away.
* Backwards-compatibility: existing primary-only configs keep working without modification.
