### ISSUE TITLE
CLI: Fix loading config via CLI when transforms are present in the yaml file

### ISSUE THREAD

**Issue by davoclavo** [sequinstream/sequin#1424]
Trying to load/plan settings that include transforms fail with the following error:

```
sequin config export > sequin.yaml

sequin config plan sequin.yaml
sequin: error: server returned error: {"summary":"Error updating transform 'record-transform': %{transform: %{path: [\"can't be blank\"]}}"}
```

The `path` attribute is present in the exported config, so there seems to be something wrong with the deserializer or loader of the config.

`sequin.yaml`
```yaml

...

transforms:
  - name: record-transform
    type: path
    path: record
    description: Extracts just the record from the Sequin message shape.
  - name: id-transform
    type: path
    path: record.id
    description: Extracts just the id column from the record. Useful if your destination only needs to know which records exist or change. Only works if your table has an id column.
```
