### ISSUE TITLE
cli bug: exporting and loading http_endpoint with encrypted headers with `--no-show-sensitive` not working properly

### ISSUE THREAD

**Issue by davoclavo** [sequinstream/sequin#1442]
Exporting and importing `http_endpoints` with encrypted headers via the CLI with `--no-show-sensitive` does not work properly.

Steps to replicate:

1. Create an `http_endpoint` **with** an encrypted header
2. Export sequin config to a yaml with `sequin config export --no-show-sensitive >| sequin.yaml`
3. Try to make a config apply diff with `sequin config plan sequin.yaml`
4. Fails with the following error:

```
sequin: error: server returned error: {"summary":"Invalid HTTP endpoint configuration: Error updating HTTP endpoint 'fragrant_water_42': Invalid headers configuration. Must be a list of key-value pairs.\n\nHTTP Endpoints are destinations for Webhook Subscriptions.\n\nThey can be configured in one of three ways:\n\n1. Configure an internet accessible URL:\n\nhttp_endpoints:\n  - name: \"external-endpoint\"\n    url: \"https://api.example.com/webhook\"\n\n2. Configure a local endpoint that uses the Sequin CLI to create a secure tunnel:\n\nhttp_endpoints:\n  - name: \"local-endpoint\"\n    local: \"true\"\n    path: \"/webhook\"\n\n3. Configure a Webhook.site endpoint for development purposes:\n\nhttp_endpoints:\n  - name: \"webhook.site-endpoint\"\n    webhook.site: \"true\"\n\n\nShared options:\n\n- name: \"some-name\"\n- headers:\n    - key: \"X-Header\"\n      value: \"my-value\"\n- encrypted_headers:\n    - key: \"X-Secret-Header\"\n      value: \"super-secret\"\n\n"}
```

`sequin.yaml` fragment:

```yaml
...

http_endpoints:
  - name: bold_sound_55
    url: http://localhost:4000/something
    headers: {}
    encrypted_headers: {}
  - name: fragrant_water_42
    url: http://localhost:4000/testing
    headers: {}
    encrypted_headers: '(1 encrypted header(s)) - sha256sum: cf529592'

...
```
